language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
- 5.3
- 5.5
- 5.6
- 7.0
- 7.1
- hhvm
- nightly
env:
- COMPOSER_FLAGS='update --prefer-lowest --prefer-stable'
- COMPOSER_FLAGS='install'
- COMPOSER_FLAGS='update'

matrix:
  exclude:
    - php: 5.3
      env: COMPOSER_FLAGS='install'
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

install:
  - composer $COMPOSER_FLAGS --prefer-dist --no-interaction

script: vendor/phpunit/phpunit/phpunit --verbose
