language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
- 5.3
- 5.5
- 5.6
- 7.0
- 7.1
- hhvm
- nightly
env:
- COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
- COMPOSER_FLAGS=''

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script: vendor/phpunit/phpunit/phpunit --verbose
