language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
- 5.6
- 7.0
- 7.1
- 7.2

env:
- COMPOSER_FLAGS='update --prefer-lowest --prefer-stable'
- COMPOSER_FLAGS='update'

matrix:
  exclude:
    - php: 7.2
      env: COMPOSER_FLAGS='update --prefer-lowest --prefer-stable'
  fast_finish: true

install:
  - composer $COMPOSER_FLAGS --prefer-dist --no-interaction

script: vendor/phpunit/phpunit/phpunit --verbose
