language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.6
    - php: 5.6
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 5.5
    - php: 5.3
    - php: 5.3
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: hhvm
    - php: nightly
    - php: 7.0
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.1
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script: vendor/phpunit/phpunit/phpunit --verbose
